# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoadExecFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadExecFile.setGeometry(QtCore.QRect(790, 230, 271, 23))
        self.btnLoadExecFile.setObjectName("btnLoadExecFile")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(800, 10, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(800, 30, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(800, 50, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(790, 210, 101, 16))
        self.label_4.setObjectName("label_4")
        self.lblExecFile = QtWidgets.QLabel(self.centralwidget)
        self.lblExecFile.setGeometry(QtCore.QRect(900, 210, 101, 16))
        self.lblExecFile.setText("")
        self.lblExecFile.setObjectName("lblExecFile")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(790, 310, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lblInputTest = QtWidgets.QLabel(self.centralwidget)
        self.lblInputTest.setGeometry(QtCore.QRect(870, 310, 131, 16))
        self.lblInputTest.setText("")
        self.lblInputTest.setObjectName("lblInputTest")
        self.nameMethod = QtWidgets.QTextEdit(self.centralwidget)
        self.nameMethod.setGeometry(QtCore.QRect(860, 50, 201, 21))
        self.nameMethod.setObjectName("nameMethod")
        self.btnLoadInputTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadInputTest.setGeometry(QtCore.QRect(790, 330, 271, 23))
        self.btnLoadInputTest.setObjectName("btnLoadInputTest")
        self.btnNextMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextMethod.setGeometry(QtCore.QRect(120, 0, 161, 23))
        self.btnNextMethod.setObjectName("btnNextMethod")
        self.btnPrevMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevMethod.setGeometry(QtCore.QRect(300, 0, 161, 23))
        self.btnPrevMethod.setObjectName("btnPrevMethod")
        self.btnDelThisMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelThisMethod.setGeometry(QtCore.QRect(620, 30, 141, 31))
        self.btnDelThisMethod.setObjectName("btnDelThisMethod")
        self.btnDelAllMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelAllMethod.setGeometry(QtCore.QRect(620, 0, 141, 31))
        self.btnDelAllMethod.setObjectName("btnDelAllMethod")
        self.btnSaveThisMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveThisMethod.setGeometry(QtCore.QRect(470, 0, 141, 31))
        self.btnSaveThisMethod.setObjectName("btnSaveThisMethod")
        self.btnSaveAllMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveAllMethod.setGeometry(QtCore.QRect(470, 30, 141, 31))
        self.btnSaveAllMethod.setObjectName("btnSaveAllMethod")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 20, 47, 13))
        self.label_8.setObjectName("label_8")
        self.lblNextMethod = QtWidgets.QLabel(self.centralwidget)
        self.lblNextMethod.setGeometry(QtCore.QRect(170, 20, 101, 16))
        self.lblNextMethod.setObjectName("lblNextMethod")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 20, 47, 13))
        self.label_10.setObjectName("label_10")
        self.lblPrevMethod = QtWidgets.QLabel(self.centralwidget)
        self.lblPrevMethod.setGeometry(QtCore.QRect(350, 20, 101, 16))
        self.lblPrevMethod.setObjectName("lblPrevMethod")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 91, 16))
        self.label_12.setObjectName("label_12")
        self.lblThisMethod = QtWidgets.QLabel(self.centralwidget)
        self.lblThisMethod.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.lblThisMethod.setObjectName("lblThisMethod")
        self.btnCalcThisMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcThisMethod.setGeometry(QtCore.QRect(10, 40, 191, 23))
        self.btnCalcThisMethod.setObjectName("btnCalcThisMethod")
        self.btnSaveTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveTest.setGeometry(QtCore.QRect(250, 40, 211, 23))
        self.btnSaveTest.setObjectName("btnSaveTest")
        self.btnSaveResByte = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveResByte.setGeometry(QtCore.QRect(250, 60, 211, 23))
        self.btnSaveResByte.setObjectName("btnSaveResByte")
        self.btnCalcTo = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcTo.setGeometry(QtCore.QRect(10, 60, 131, 23))
        self.btnCalcTo.setObjectName("btnCalcTo")
        self.spnToMethod = QtWidgets.QSpinBox(self.centralwidget)
        self.spnToMethod.setGeometry(QtCore.QRect(140, 60, 61, 22))
        self.spnToMethod.setMaximum(999999999)
        self.spnToMethod.setObjectName("spnToMethod")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(270, 90, 101, 16))
        self.label_15.setObjectName("label_15")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(690, 330, 71, 23))
        self.btnExit.setObjectName("btnExit")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 330, 201, 21))
        self.label_16.setObjectName("label_16")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(200, 330, 61, 21))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 330, 61, 16))
        self.label_5.setObjectName("label_5")
        self.lblMsg = QtWidgets.QLabel(self.centralwidget)
        self.lblMsg.setGeometry(QtCore.QRect(340, 330, 341, 16))
        self.lblMsg.setText("")
        self.lblMsg.setObjectName("lblMsg")
        self.btnAddMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddMethod.setGeometry(QtCore.QRect(790, 160, 271, 31))
        self.btnAddMethod.setObjectName("btnAddMethod")
        self.cmbMethods = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMethods.setGeometry(QtCore.QRect(860, 30, 201, 22))
        self.cmbMethods.setObjectName("cmbMethods")
        self.btnLoadMethods = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadMethods.setGeometry(QtCore.QRect(470, 60, 291, 21))
        self.btnLoadMethods.setObjectName("btnLoadMethods")
        self.tblInutTest = QtWidgets.QTableWidget(self.centralwidget)
        self.tblInutTest.setGeometry(QtCore.QRect(10, 110, 251, 221))
        self.tblInutTest.setObjectName("tblInutTest")
        self.tblInutTest.setColumnCount(0)
        self.tblInutTest.setRowCount(0)
        self.tblRes = QtWidgets.QTableWidget(self.centralwidget)
        self.tblRes.setGeometry(QtCore.QRect(270, 110, 491, 221))
        self.tblRes.setObjectName("tblRes")
        self.tblRes.setColumnCount(0)
        self.tblRes.setRowCount(0)
        self.btnLoadResFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadResFile.setGeometry(QtCore.QRect(790, 280, 271, 23))
        self.btnLoadResFile.setObjectName("btnLoadResFile")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(790, 260, 101, 16))
        self.label_7.setObjectName("label_7")
        self.lblResFile = QtWidgets.QLabel(self.centralwidget)
        self.lblResFile.setGeometry(QtCore.QRect(900, 260, 101, 16))
        self.lblResFile.setText("")
        self.lblResFile.setObjectName("lblResFile")
        self.spnCountThread = QtWidgets.QSpinBox(self.centralwidget)
        self.spnCountThread.setGeometry(QtCore.QRect(800, 90, 61, 22))
        self.spnCountThread.setMaximum(999999999)
        self.spnCountThread.setObjectName("spnCountThread")
        self.spnTimeWait = QtWidgets.QSpinBox(self.centralwidget)
        self.spnTimeWait.setGeometry(QtCore.QRect(1000, 110, 61, 22))
        self.spnTimeWait.setMaximum(999999999)
        self.spnTimeWait.setObjectName("spnTimeWait")
        self.spnSleepWork = QtWidgets.QSpinBox(self.centralwidget)
        self.spnSleepWork.setGeometry(QtCore.QRect(910, 90, 61, 22))
        self.spnSleepWork.setMaximum(999999999)
        self.spnSleepWork.setObjectName("spnSleepWork")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(790, 70, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(790, 110, 211, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(900, 70, 141, 16))
        self.label_13.setObjectName("label_13")
        self.spnCountRowEnd = QtWidgets.QSpinBox(self.centralwidget)
        self.spnCountRowEnd.setGeometry(QtCore.QRect(1020, 130, 41, 22))
        self.spnCountRowEnd.setMaximum(999999999)
        self.spnCountRowEnd.setObjectName("spnCountRowEnd")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(790, 130, 171, 21))
        self.label_17.setObjectName("label_17")
        self.spnCountRowStart = QtWidgets.QSpinBox(self.centralwidget)
        self.spnCountRowStart.setGeometry(QtCore.QRect(960, 130, 41, 22))
        self.spnCountRowStart.setMaximum(999999999)
        self.spnCountRowStart.setObjectName("spnCountRowStart")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1000, 130, 16, 16))
        self.label_18.setObjectName("label_18")
        self.lblResFile_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblResFile_2.setGeometry(QtCore.QRect(900, 260, 131, 16))
        self.lblResFile_2.setText("")
        self.lblResFile_2.setObjectName("lblResFile_2")
        self.tblChgTest = QtWidgets.QTableWidget(self.centralwidget)
        self.tblChgTest.setGeometry(QtCore.QRect(10, 360, 501, 221))
        self.tblChgTest.setObjectName("tblChgTest")
        self.tblChgTest.setColumnCount(5)
        self.tblChgTest.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(4, item)
        self.btnAddStrEditTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddStrEditTest.setGeometry(QtCore.QRect(510, 360, 91, 23))
        self.btnAddStrEditTest.setObjectName("btnAddStrEditTest")
        self.prgExec = QtWidgets.QProgressBar(self.centralwidget)
        self.prgExec.setGeometry(QtCore.QRect(610, 380, 451, 23))
        self.prgExec.setProperty("value", 0)
        self.prgExec.setObjectName("prgExec")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(510, 380, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(610, 360, 71, 16))
        self.label_19.setObjectName("label_19")
        self.lblExecuteProc = QtWidgets.QLabel(self.centralwidget)
        self.lblExecuteProc.setGeometry(QtCore.QRect(690, 360, 371, 16))
        self.lblExecuteProc.setText("")
        self.lblExecuteProc.setObjectName("lblExecuteProc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализ данных"))
        self.btnLoadExecFile.setText(_translate("MainWindow", "Загрузить исполняемый файл"))
        self.label.setText(_translate("MainWindow", "Добавить метод:"))
        self.label_2.setText(_translate("MainWindow", "Тип:"))
        self.label_3.setText(_translate("MainWindow", "Название:"))
        self.label_4.setText(_translate("MainWindow", "Исполняемый файл:"))
        self.label_6.setText(_translate("MainWindow", "Входной тест:"))
        self.btnLoadInputTest.setText(_translate("MainWindow", "Загрузить тест"))
        self.btnNextMethod.setText(_translate("MainWindow", "Следующий метод:"))
        self.btnPrevMethod.setText(_translate("MainWindow", "Предыдущий метод:"))
        self.btnDelThisMethod.setText(_translate("MainWindow", "Удалить текущий метод"))
        self.btnDelAllMethod.setText(_translate("MainWindow", "Удалить все методы"))
        self.btnSaveThisMethod.setText(_translate("MainWindow", "Сохранить этот метод"))
        self.btnSaveAllMethod.setText(_translate("MainWindow", "Сохранить все методы"))
        self.label_8.setText(_translate("MainWindow", "Метод:"))
        self.lblNextMethod.setText(_translate("MainWindow", "NO"))
        self.label_10.setText(_translate("MainWindow", "Метод:"))
        self.lblPrevMethod.setText(_translate("MainWindow", "NO"))
        self.label_12.setText(_translate("MainWindow", "Текущий метод:"))
        self.lblThisMethod.setText(_translate("MainWindow", "NO"))
        self.btnCalcThisMethod.setText(_translate("MainWindow", "Вычислить"))
        self.btnSaveTest.setText(_translate("MainWindow", "Сохранить тест"))
        self.btnSaveResByte.setText(_translate("MainWindow", "Сохранить результат в тест"))
        self.btnCalcTo.setText(_translate("MainWindow", "Вычислить до метода:"))
        self.label_14.setText(_translate("MainWindow", "Входные данные:"))
        self.label_15.setText(_translate("MainWindow", "Выходные данные:"))
        self.btnExit.setText(_translate("MainWindow", "Выход"))
        self.label_16.setText(_translate("MainWindow", "Время выполнения теста (секунды):"))
        self.label_5.setText(_translate("MainWindow", "Сообщение:"))
        self.btnAddMethod.setText(_translate("MainWindow", "Добавить метод"))
        self.btnLoadMethods.setText(_translate("MainWindow", "Загрузить метод(ы)"))
        self.btnLoadResFile.setText(_translate("MainWindow", "Загрузить результирующий файл"))
        self.label_7.setText(_translate("MainWindow", "Фул с результатом:"))
        self.label_9.setText(_translate("MainWindow", "Кол-во потоков:"))
        self.label_11.setText(_translate("MainWindow", "Максимальное время ожидания потока:"))
        self.label_13.setText(_translate("MainWindow", "Ожидание после запуска:"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Строки проверки(без последней) </p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "   -"))
        item = self.tblChgTest.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Адрес байта"))
        item = self.tblChgTest.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Содержимое"))
        item = self.tblChgTest.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Готово"))
        item = self.tblChgTest.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Убрать"))
        item = self.tblChgTest.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Поиск по адресу"))
        self.btnAddStrEditTest.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_4.setText(_translate("MainWindow", "Применить все"))
        self.label_19.setText(_translate("MainWindow", "Выполнение:"))

