# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1651, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoadExecFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadExecFile.setGeometry(QtCore.QRect(1280, 130, 271, 31))
        self.btnLoadExecFile.setObjectName("btnLoadExecFile")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(730, 10, 91, 16))
        self.label.setObjectName("label")
        self.lblType = QtWidgets.QLabel(self.centralwidget)
        self.lblType.setGeometry(QtCore.QRect(730, 30, 41, 16))
        self.lblType.setObjectName("lblType")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(730, 50, 61, 16))
        self.lblName.setObjectName("lblName")
        self.lblExecFileHeader = QtWidgets.QLabel(self.centralwidget)
        self.lblExecFileHeader.setGeometry(QtCore.QRect(1280, 110, 101, 16))
        self.lblExecFileHeader.setObjectName("lblExecFileHeader")
        self.lblExecFile = QtWidgets.QLabel(self.centralwidget)
        self.lblExecFile.setGeometry(QtCore.QRect(1380, 110, 171, 16))
        self.lblExecFile.setText("")
        self.lblExecFile.setObjectName("lblExecFile")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1280, 210, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lblInputTest = QtWidgets.QLabel(self.centralwidget)
        self.lblInputTest.setGeometry(QtCore.QRect(1360, 210, 191, 16))
        self.lblInputTest.setText("")
        self.lblInputTest.setObjectName("lblInputTest")
        self.nameMethod = QtWidgets.QTextEdit(self.centralwidget)
        self.nameMethod.setGeometry(QtCore.QRect(790, 50, 221, 21))
        self.nameMethod.setObjectName("nameMethod")
        self.btnLoadInputTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadInputTest.setGeometry(QtCore.QRect(1280, 230, 271, 31))
        self.btnLoadInputTest.setObjectName("btnLoadInputTest")
        self.btnNextMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextMethod.setGeometry(QtCore.QRect(720, 280, 31, 31))
        self.btnNextMethod.setText("")
        self.btnNextMethod.setObjectName("btnNextMethod")
        self.btnPrevMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevMethod.setGeometry(QtCore.QRect(720, 310, 31, 31))
        self.btnPrevMethod.setText("")
        self.btnPrevMethod.setObjectName("btnPrevMethod")
        self.btnDelThisMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelThisMethod.setGeometry(QtCore.QRect(840, 210, 51, 41))
        self.btnDelThisMethod.setText("")
        self.btnDelThisMethod.setObjectName("btnDelThisMethod")
        self.btnDelAllMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelAllMethod.setGeometry(QtCore.QRect(900, 210, 51, 41))
        self.btnDelAllMethod.setText("")
        self.btnDelAllMethod.setObjectName("btnDelAllMethod")
        self.lblNextMethod = QtWidgets.QLabel(self.centralwidget)
        self.lblNextMethod.setGeometry(QtCore.QRect(770, 280, 161, 31))
        self.lblNextMethod.setObjectName("lblNextMethod")
        self.lblPrevMethod = QtWidgets.QLabel(self.centralwidget)
        self.lblPrevMethod.setGeometry(QtCore.QRect(770, 310, 161, 31))
        self.lblPrevMethod.setObjectName("lblPrevMethod")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(720, 260, 91, 16))
        self.label_12.setObjectName("label_12")
        self.lblThisMethod = QtWidgets.QLabel(self.centralwidget)
        self.lblThisMethod.setGeometry(QtCore.QRect(810, 260, 161, 16))
        self.lblThisMethod.setObjectName("lblThisMethod")
        self.btnCalcThisMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcThisMethod.setGeometry(QtCore.QRect(960, 210, 51, 41))
        self.btnCalcThisMethod.setText("")
        self.btnCalcThisMethod.setObjectName("btnCalcThisMethod")
        self.btnSaveTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveTest.setGeometry(QtCore.QRect(1290, 30, 161, 31))
        self.btnSaveTest.setObjectName("btnSaveTest")
        self.btnSaveResByte = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveResByte.setGeometry(QtCore.QRect(1330, 190, 101, 31))
        self.btnSaveResByte.setObjectName("btnSaveResByte")
        self.btnCalcTo = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcTo.setGeometry(QtCore.QRect(1030, 640, 131, 23))
        self.btnCalcTo.setObjectName("btnCalcTo")
        self.spnToMethod = QtWidgets.QSpinBox(self.centralwidget)
        self.spnToMethod.setGeometry(QtCore.QRect(1160, 640, 41, 22))
        self.spnToMethod.setMaximum(999999999)
        self.spnToMethod.setObjectName("spnToMethod")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 370, 101, 16))
        self.label_15.setObjectName("label_15")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(930, 610, 91, 31))
        self.btnExit.setObjectName("btnExit")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(300, 620, 191, 21))
        self.label_16.setObjectName("label_16")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(490, 620, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 620, 61, 16))
        self.label_5.setObjectName("label_5")
        self.lblMsg = QtWidgets.QLabel(self.centralwidget)
        self.lblMsg.setGeometry(QtCore.QRect(80, 620, 211, 16))
        self.lblMsg.setText("")
        self.lblMsg.setObjectName("lblMsg")
        self.btnAddMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddMethod.setGeometry(QtCore.QRect(720, 210, 51, 41))
        self.btnAddMethod.setText("")
        self.btnAddMethod.setObjectName("btnAddMethod")
        self.cmbMethods = QtWidgets.QComboBox(self.centralwidget)
        self.cmbMethods.setGeometry(QtCore.QRect(790, 30, 221, 22))
        self.cmbMethods.setObjectName("cmbMethods")
        self.tblInutTest = QtWidgets.QTableWidget(self.centralwidget)
        self.tblInutTest.setGeometry(QtCore.QRect(10, 30, 701, 331))
        self.tblInutTest.setObjectName("tblInutTest")
        self.tblInutTest.setColumnCount(0)
        self.tblInutTest.setRowCount(0)
        self.tblRes = QtWidgets.QTableWidget(self.centralwidget)
        self.tblRes.setGeometry(QtCore.QRect(10, 390, 1011, 211))
        self.tblRes.setObjectName("tblRes")
        self.tblRes.setColumnCount(0)
        self.tblRes.setRowCount(0)
        self.btnLoadResFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadResFile.setGeometry(QtCore.QRect(1280, 180, 271, 31))
        self.btnLoadResFile.setObjectName("btnLoadResFile")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1280, 160, 111, 16))
        self.label_7.setObjectName("label_7")
        self.lblResFile = QtWidgets.QLabel(self.centralwidget)
        self.lblResFile.setGeometry(QtCore.QRect(1390, 160, 161, 16))
        self.lblResFile.setText("")
        self.lblResFile.setObjectName("lblResFile")
        self.spnTimeWait = QtWidgets.QSpinBox(self.centralwidget)
        self.spnTimeWait.setGeometry(QtCore.QRect(930, 80, 81, 22))
        self.spnTimeWait.setMaximum(999999999)
        self.spnTimeWait.setObjectName("spnTimeWait")
        self.lblTimeWait = QtWidgets.QLabel(self.centralwidget)
        self.lblTimeWait.setGeometry(QtCore.QRect(720, 80, 211, 21))
        self.lblTimeWait.setObjectName("lblTimeWait")
        self.lblBytes = QtWidgets.QLabel(self.centralwidget)
        self.lblBytes.setGeometry(QtCore.QRect(720, 110, 291, 21))
        self.lblBytes.setObjectName("lblBytes")
        self.tblChgTest = QtWidgets.QTableWidget(self.centralwidget)
        self.tblChgTest.setGeometry(QtCore.QRect(1410, -10, 651, 191))
        self.tblChgTest.setObjectName("tblChgTest")
        self.tblChgTest.setColumnCount(6)
        self.tblChgTest.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblChgTest.setHorizontalHeaderItem(5, item)
        self.btnAddStrEditTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddStrEditTest.setGeometry(QtCore.QRect(1180, 70, 41, 31))
        self.btnAddStrEditTest.setText("")
        self.btnAddStrEditTest.setObjectName("btnAddStrEditTest")
        self.prgExec = QtWidgets.QProgressBar(self.centralwidget)
        self.prgExec.setGeometry(QtCore.QRect(670, 619, 261, 21))
        self.prgExec.setProperty("value", 0)
        self.prgExec.setObjectName("prgExec")
        self.btnChgAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnChgAll.setGeometry(QtCore.QRect(1180, 110, 71, 31))
        self.btnChgAll.setText("")
        self.btnChgAll.setObjectName("btnChgAll")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(600, 620, 71, 16))
        self.label_19.setObjectName("label_19")
        self.lblExecuteProc = QtWidgets.QLabel(self.centralwidget)
        self.lblExecuteProc.setGeometry(QtCore.QRect(670, 620, 231, 21))
        self.lblExecuteProc.setText("")
        self.lblExecuteProc.setObjectName("lblExecuteProc")
        self.btnOpenInputData = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenInputData.setGeometry(QtCore.QRect(1350, 140, 81, 31))
        self.btnOpenInputData.setObjectName("btnOpenInputData")
        self.btnOpenResData = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenResData.setGeometry(QtCore.QRect(1220, 30, 81, 31))
        self.btnOpenResData.setObjectName("btnOpenResData")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1280, 90, 91, 16))
        self.label_20.setObjectName("label_20")
        self.btnClearChgAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnClearChgAll.setGeometry(QtCore.QRect(1180, 190, 71, 31))
        self.btnClearChgAll.setText("")
        self.btnClearChgAll.setObjectName("btnClearChgAll")
        self.btnFindChgAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnFindChgAll.setGeometry(QtCore.QRect(1180, 230, 71, 31))
        self.btnFindChgAll.setText("")
        self.btnFindChgAll.setObjectName("btnFindChgAll")
        self.btnStartAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartAll.setGeometry(QtCore.QRect(1180, 150, 71, 31))
        self.btnStartAll.setText("")
        self.btnStartAll.setObjectName("btnStartAll")
        self.lblStartAllPos = QtWidgets.QLabel(self.centralwidget)
        self.lblStartAllPos.setGeometry(QtCore.QRect(720, 120, 291, 21))
        self.lblStartAllPos.setObjectName("lblStartAllPos")
        self.lblToCount = QtWidgets.QLabel(self.centralwidget)
        self.lblToCount.setGeometry(QtCore.QRect(720, 160, 291, 21))
        self.lblToCount.setObjectName("lblToCount")
        self.txtPosStart = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPosStart.setGeometry(QtCore.QRect(720, 140, 291, 21))
        self.txtPosStart.setObjectName("txtPosStart")
        self.txtPosEnd = QtWidgets.QTextEdit(self.centralwidget)
        self.txtPosEnd.setGeometry(QtCore.QRect(720, 180, 291, 21))
        self.txtPosEnd.setObjectName("txtPosEnd")
        self.btnEditMethod = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditMethod.setGeometry(QtCore.QRect(780, 210, 51, 41))
        self.btnEditMethod.setText("")
        self.btnEditMethod.setObjectName("btnEditMethod")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1651, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.actLoadTest = QtWidgets.QAction(MainWindow)
        self.actLoadTest.setObjectName("actLoadTest")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_3.addAction(self.actLoadTest)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализ данных"))
        self.btnLoadExecFile.setText(_translate("MainWindow", "Загрузить исполняемый файл"))
        self.label.setText(_translate("MainWindow", "Добавить метод:"))
        self.lblType.setText(_translate("MainWindow", "Тип:"))
        self.lblName.setText(_translate("MainWindow", "Название:"))
        self.lblExecFileHeader.setText(_translate("MainWindow", "Исполняемый файл:"))
        self.label_6.setText(_translate("MainWindow", "Входной тест:"))
        self.btnLoadInputTest.setText(_translate("MainWindow", "Загрузить тест"))
        self.lblNextMethod.setText(_translate("MainWindow", "NO"))
        self.lblPrevMethod.setText(_translate("MainWindow", "NO"))
        self.label_12.setText(_translate("MainWindow", "Текущий метод:"))
        self.lblThisMethod.setText(_translate("MainWindow", "NO"))
        self.btnSaveTest.setText(_translate("MainWindow", "Сохранить результат"))
        self.btnSaveResByte.setText(_translate("MainWindow", "Сохранить тест"))
        self.btnCalcTo.setText(_translate("MainWindow", "Вычислить до метода:"))
        self.label_14.setText(_translate("MainWindow", "Входные данные:"))
        self.label_15.setText(_translate("MainWindow", "Выходные данные:"))
        self.btnExit.setText(_translate("MainWindow", "Выход"))
        self.label_16.setText(_translate("MainWindow", "Время выполнения теста (секунды):"))
        self.label_5.setText(_translate("MainWindow", "Сообщение:"))
        self.btnLoadResFile.setText(_translate("MainWindow", "Загрузить результирующий файл"))
        self.label_7.setText(_translate("MainWindow", "Файл с результатом:"))
        self.lblTimeWait.setText(_translate("MainWindow", "Максимальное время ожидания потока:"))
        self.lblBytes.setText(_translate("MainWindow", "<html><head/><body><p>Байты проверки (с последним)</p><p><br/></p></body></html>"))
        item = self.tblChgTest.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Адрес байта"))
        item = self.tblChgTest.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Содержимое"))
        item = self.tblChgTest.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Готово"))
        item = self.tblChgTest.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Начальное"))
        item = self.tblChgTest.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Поиск по адресу"))
        item = self.tblChgTest.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Убрать"))
        self.label_19.setText(_translate("MainWindow", "Выполнение:"))
        self.btnOpenInputData.setText(_translate("MainWindow", "Развернуть"))
        self.btnOpenResData.setText(_translate("MainWindow", "Развернуть"))
        self.label_20.setText(_translate("MainWindow", "Добавить Файлы:"))
        self.lblStartAllPos.setText(_translate("MainWindow", "с"))
        self.lblToCount.setText(_translate("MainWindow", "по"))
        self.menu.setTitle(_translate("MainWindow", "Развернуть"))
        self.menu_2.setTitle(_translate("MainWindow", "Сохранить"))
        self.menu_3.setTitle(_translate("MainWindow", "Загрузить"))
        self.action.setText(_translate("MainWindow", "Тест"))
        self.action_2.setText(_translate("MainWindow", "Результат"))
        self.action_3.setText(_translate("MainWindow", "Тест"))
        self.action_4.setText(_translate("MainWindow", "Результат"))
        self.actLoadTest.setText(_translate("MainWindow", "Тест"))


